#!/usr/bin/env bash
#Sets nginx for listening to 80 port
sed -i "s/8080/80/" /etc/nginx/sites-enabled/default
sudo service nginx restart
kill -9 "$(cat /var/run/nginx.pid)"
service nginx status | grep -q "not running" && echo " * nginx is not running"
